version: '2'
services:
  node:
    networks: 
      - nodejs-the-complete-guide
    build:
      context: ./
      dockerfile: dockerfile
    volumes:
      - ./src/:/app
    links:
      - database
    environment:
      - 'DB_PORT=3306'
      - 'DB_HOST=database'
    ports:
      - '7000:3000'
  database:
    image: mysql:8.0.23
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
        - 'MYSQL_ROOT_PASSWORD=V4pQNJYuyHeDRAbNuMUjxwqL4raCAVUE'
        - 'MYSQL_DATABASE=app'
    ports:
      - '7006:3306'
networks:
  nodejs-the-complete-guide:
    external: true
    name: nodejs-the-complete-guide
